### ISSUE TITLE
You shouldn't put the ads

### ISSUE THREAD

**Issue by hatemswaileh** [SafaErden/The-New-York-Times#3]
Hello @vanheaven-ui & @SafaErden 
- [x] You shouldn't put the ads on the website, it's one of the requirements for the project

Please don't hate me 😄

**Comment by vanheaven-ui** [comment]
We are using them to account for extra space on the page

**Comment by hatemsweileh** [comment]
Yes, you told me and sorry for that but I have to do it so I can include it in the form, sorry again 😄
